### ISSUE TITLE
Unable to navigate back to exit the application from the Survey screen

### ISSUE THREAD

**Issue by hoangnguyen92dn** [daaaniii98/nimble-survey#2]
I noticed that the application doesn't allow users to navigate back to exit from the Survey screen

https://user-images.githubusercontent.com/6950766/147057883-f6193d51-41be-44de-a106-bdcbdf6300a8.mp4

**Comment by daaaniii98** [comment]
There were two navigation issues resolved: 
1 - User won't be able to navigate back from Survey Screen (Exit)
2 - User won't be able to exit app from login after logging out from the App (SurveyScreen -> Logout -> LoginScreen)

**Comment by hoangnguyen92dn** [comment]
@daaaniii98 Can you please kindly create separate PRs to apply the fix for the next upcoming updates? It's also easier for us to review code changes linked to the created issues. Thank you.
