### ISSUE TITLE
Get rid of @SuppressLint("WrongConstant") annotation

### ISSUE THREAD

**Issue by hoangnguyen92dn** [daaaniii98/nimble-survey#4]
I think the error is shown on `openDrawer(Gravity.END) ` is valid, would it be possible to resolve following the message rather than skip it?

![Screen Shot 2021-12-22 at 16 23 14](https://user-images.githubusercontent.com/6950766/147069057-6546e57f-d10e-4aa5-9181-286ec101e952.png)

https://github.com/daaaniii98/nimble-survey/blob/93c8d2394d08ecc57088e8b5218c0877fa69783c/app/src/main/java/com/yorbax/nimblesurvey/ui/survey_home/SurveyFragment.kt#L47-L49

https://github.com/daaaniii98/nimble-survey/blob/93c8d2394d08ecc57088e8b5218c0877fa69783c/app/src/main/java/com/yorbax/nimblesurvey/ui/survey_home/SurveyFragment.kt#L97-L99

**Comment by daaaniii98** [comment]
Issue resolved in **"Ticket # 4"**
