### ISSUE TITLE
Secret the API credentials with the build process

### ISSUE THREAD

**Issue by hoangnguyen92dn** [daaaniii98/nimble-survey#5]
With your current implementation, the API credentials could be leaked by reverse engineering. I suggest configuring the credentials secret with the build process, how do you think?

https://github.com/daaaniii98/nimble-survey/blob/93c8d2394d08ecc57088e8b5218c0877fa69783c/app/src/main/java/com/yorbax/nimblesurvey/constant/MyConstants.kt#L3-L6

**Comment by daaaniii98** [comment]
Issue resolved [Here](https://github.com/daaaniii98/nimble-survey/pull/11/commits/c1cf9065b33f9e9fd1215428459b47ac9b72649a)
