### ISSUE TITLE
Redundant attributes on activity_main.xml layout

### ISSUE THREAD

**Issue by hoangnguyen92dn** [daaaniii98/nimble-survey#6]
The layout width and height are set as `match_parent` but still use the constraints to anchor the layout. Would it be possible to get rid of redundant attributes usage?

https://github.com/daaaniii98/nimble-survey/blob/93c8d2394d08ecc57088e8b5218c0877fa69783c/app/src/main/res/layout/activity_main.xml#L9-L19

**Comment by daaaniii98** [comment]
Issue resolved [Here](https://github.com/daaaniii98/nimble-survey/pull/10/commits/453fda841b85c3da477ad1162c01bd6bedaceebe)
