### ISSUE TITLE
There are some package, classes violating naming convention

### ISSUE THREAD

**Issue by hoangnguyen92dn** [daaaniii98/nimble-survey#7]
I see that there are some packages and classes named with weird patterns (`Network`, `survey_item`, `LoginUnitTest`, ...); according to [Kotlin style guide](https://developer.android.com/kotlin/style-guide) from the Android developer site, I'd recommend following the convention for consistency. How do you think?

![image](https://user-images.githubusercontent.com/6950766/147071579-9de400af-2fe0-4d48-9adc-42d6ba8d3d52.png)

https://github.com/daaaniii98/nimble-survey/blob/c5d5f87ecfa6defe91be2b66448a8e6440c214eb/app/src/test/java/com/yorbax/nimblesurvey/LoginUnitTest.kt#L30-L33

https://github.com/daaaniii98/nimble-survey/blob/c5d5f87ecfa6defe91be2b66448a8e6440c214eb/app/src/test/java/com/yorbax/nimblesurvey/SurveyUnitTest.kt#L31-L35

P/s: I also noticed the `UserDB` class is actually a wrapper class using SharedPreferences, so named `DB` makes me confused.

**Comment by daaaniii98** [comment]
Issue resolved [Here](https://github.com/daaaniii98/nimble-survey/pull/13/commits/9733f8047b29e3cd45f4c9e545dcfb9c37598048)
