### ISSUE TITLE
There is an issue related to applying Singleton pattern with DI library

### ISSUE THREAD

**Issue by hoangnguyen92dn** [daaaniii98/nimble-survey#8]
The Singleton pattern is a good approach to manage a single instance for usage and keep it alive belonging to the application lifecycle, I see you are applying the pattern to `UserDB.kt` and the `SurveyDatabase` with `getInstance` method, besides that you also using `single` to initialize the instance. It's quite redundant due to the Koin library already mange the instance as Singleton for us. What do you think about this?

https://github.com/daaaniii98/nimble-survey/blob/c5d5f87ecfa6defe91be2b66448a8e6440c214eb/app/src/main/java/com/yorbax/nimblesurvey/di/surveyModule.kt#L12-L16

https://github.com/daaaniii98/nimble-survey/blob/c5d5f87ecfa6defe91be2b66448a8e6440c214eb/app/src/main/java/com/yorbax/nimblesurvey/di/appModules.kt#L9-L12

**Comment by daaaniii98** [comment]
Issue Solved [Here](https://github.com/daaaniii98/nimble-survey/pull/12/commits/ab9c513e1ad2b7bff78b39025eea510cdaf253b0)
